title: Portfólio de Projetos - Bruno Oliveira
description: Página inicial para resumo e apresentação dos projetos em Análise de Dados.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate



